# Generated by Django 4.0.2 on 2022-08-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['id'], 'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
    ]
